# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-06 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(db_column='publisher_name', max_length=30),
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='zt_book',
        ),
    ]
