# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-07 05:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guan', '0003_auto_20200306_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuanGuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('guan_point', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'guanguan',
            },
        ),
        migrations.AlterField(
            model_name='guantype',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='guantype',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='guanguan',
            name='guan_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guan.GuanType'),
        ),
    ]
